version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE:  "${MYSQL_DATABASE_NAME}"

  adminer:
    image: adminer
    restart: on-failure
    links:
      - "db:db"
    ports:
      - ${ADMINER_PORT:-8080}:8080
